# -*- coding: utf-8 -*-
"""Week_5_lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uFqu5RZpz2iWukLbpW3B0t3D2Yhzpo93

## Importing Libraries
"""

import pandas as pd

# Read the CSV file
data = pd.read_csv("YelloTaxiData.csv")

# Visualising the data
data.head()

# Deleting from the 101st row till the last row
data = data.drop(data.index[100:])

data.tail()

# Saving dataframe to a new csv file
data.to_csv("YelloTaxiData_new.csv", index=False)